spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/planService
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
