spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:umut.aws.g@gmail.com}
    password: ${MAIL_PASSWORD:cypkvtkujrbdvarl}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9080

