spring:
  kafka:
    bootstrap-servers: kafka-1:29092
  data:
    mongodb:
      uri: mongodb://root:root@notification-service-db:27017/notification-service?authSource=admin
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true