spring:
  data:
    mongodb:
      uri: mongodb://mongouser:mongopassword@product-service:27019/crm?authSource=admin
      username: mongouser
      password: mongopassword
      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server-app:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true