spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
management:
    endpoints:
        web:
            exposure:
                include: "*"
    enpoint:
        health:
            show-details: always
    metrics:
        export:
            prometheus:
                enabled: true
    tracing:
        sampling:
            probability: 1.0