eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  datasource:
    url: "jdbc:postgresql://contract-service-db:5432/contract_service"
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: kafka-1:9092
          autoCreateTopics: true

  kafka:
    bootstrap-servers: kafka-1:9092
