spring:
  datasource:
  url: "jdbc:postgresql://localhost:5436/contract_service"
  username: postgres
  password: test
  driver-class-name: org.postgresql.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
