spring:
  application:
    name: payment-service
  jpa:
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 9050

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework.cloud.stream: DEBUG
    org.springframework.kafka: DEBUG # Spring Kafka bileşenleri için
    org.apache.kafka.clients.producer: DEBUG # Kafka producer detayları için