spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/payment-db"
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  cloud:
    function:
      definition: paymentSuccessFunction;paymentFailedFunction;billCreatedFunction;billPaidFunction;billOverdueFunction
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: localhost:29092
          autoCreateTopics: true
    bindings:
      paymentSuccessFunction-out-0:
        destination: payment-success-topic
        content-type: application/json
      paymentFailedFunction-out-0:
        destination: payment-failed-topic
        content-type: application/json
      billCreatedFunction-out-0:
        destination: bill-created-topic
        content-type: application/json
      billPaidFunction-out-0:
        destination: bill-paid-topic
        content-type: application/json
      billOverdueFunction-out-0:
        destination: bill-overdue-topic
        content-type: application/json

server:
  port: 9050

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.gygy.paymentservice: DEBUG
    org.springframework.cloud.stream: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
