eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    url: "jdbc:postgresql://user-service-db:5432/user-service"
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka-1:9092  
  