eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    url: "jdbc:postgresql://user-service-db:5434/user-service"
    username: postgres
    password: test
  kafka:
    bootstrap-servers: localhost:9092  
  