spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/user-service"
    username: postgres
    password: test
  kafka:
    bootstrap-servers: localhost:9092
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    com.gygy.userservice.core.pipeline: DEBUG
    com.gygy: INFO
    root: WARN