eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8888/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  datasource:
    url: "jdbc:postgresql://customer-service-db:5432/customer-service"
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: "mongodb://mongo:test@customer-service-mongodb:27017/customer-service?authSource=admin"
      database: customer-service

  kafka:
    bootstrap-servers: kafka-1:9092  