spring:
  datasource:
    write:
      url: "jdbc:postgresql://localhost:5437/customer-service"
      username: postgres
      password: test
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
