spring:
  datasource:
    url: "jdbc:postgresql://localhost:5437/customer-service"
    username: postgres
    password: test
  data:
    mongodb:
      uri: "mongodb://mongo:test@localhost:27020,localhost:27021,localhost:27022/customer-service?replicaSet=rs0&authSource=admin"
      database: customer-service

  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
